title: Mental Health LLM Evaluation Framework
description: Framework for evaluating LLM responses in mental health contexts
theme: jekyll-theme-minimal
show_downloads: true

# Build settings
markdown: GFM
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# GitHub Pages settings
baseurl: "/mental_health_llm_eval"
url: "https://dccooper.github.io"

# Navigation
nav:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Usage
    url: /usage
  - title: API Reference
    url: /api
  - title: Contributing
    url: /contributing 